---
---

# {.tabset}

## En
 
 <h1> The Team</h1>
 <div id="sub"> Our Team combines creative, technical, and strategic talents. Meet us! </div>
 
<p>

![**Prof. Dr. Frank Klawonn**<br> 
Supervisor of the project Pain2D<br>
Mathematician and Computer scientist, Professor at the Institute of Information Engineering at Ostfalia - University of Applied Sciences in Wolfenbüttel. <br>
Head of the project group "Bioinformatics and Statistics" at the Helmholtz Centre for Infection Research in Braunschweig <br>
E-Mail: f.klawonn@ostfalia.de](img/klawonn.png)

![**M.Sc. Natasza Karolina Szczypien**<br>
Developer of Pain2D<br>
PhD Student in Computer Science at TU Braunschweig.<br>
Research Fellow at the Institute of Information Engineering Ostfalia - University of Applied Sciences.<br> 
E-Mail: na.szczypien@ostfalia.de
](img/Natasza Karolina Szczypien.png)

![**B.Sc. Nefissa Khedher** <br>
Developer of this website<br>
Student at Ostfalia - University of Applied Sciences.<br> 
Research assistant at the Institute of Information Engineering  at Ostfalia - University of Applied Sciences.<br> 
E-Mail: n.khedher@ostfalia.de
](img/Nefissa.png)

![**Dr. Julia Illgen **<br> 
Preparing the tutorial<br>
Student at Ostfalia - University of Applied Sciences.<br>
Research assistant at the Institute of Information Engineering  at Ostfalia - University of Applied Sciences.<br> 
E-Mail: j.illgen@ostfalia.de
](img/Julia.png)

</p>

## De

 <h1> Das Team </h1>
 <div id="sub"> Unser Team vereint kreative, technische und strategische Talente. Treffen Sie uns!! </div>

<p>

![**Prof. Dr. Frank Klawonn**<br> 
Projektleiter von Pain2D <br>
Mathematiker und Informatiker, Professor am Institut für Information Engineering an der Ostfalia - Hochschule für angewandte Wissenschaften in Wolfenbüttel.<br>
Leiter der Projektgruppe "Bioinformatics and Statistics" am Helmholtz-Zentrum für Infektionsforschung in Braunschweig <br>
E-Mail: f.klawonn@ostfalia.de](img/klawonn.png)


![**M.Sc. Natasza Karolina Szczypien**<br>
Entwickler von Pain2D<br>
Doktorandin in der Informatik an der TU Braunschweig.<br>
Wissenschaftliche Mitarbeiterin am Institut für Information Engineering an der Ostfalia - Hochschule für angewandte Wissenschaften.<br>
E-Mail: na.szczypien@ostfalia.de](img/Natasza Karolina Szczypien.png)


![**Nefissa Khedher **<br>
Entwickler dieser Webseite<br>
Studentin an der Ostfalia - Hochschule für angewandte Wissenschaften.<br> 
Studentische Hilfskraft am Institut für Information Engineering an der Ostfalia - Hochschule für angewandte Wissenschaften <br>
E-Mail: n.khedher@ostfalia.de](img/Nefissa.png)

![**Dr. Julia Illgen **<br> 
Entwickler des Tutorials <br>
Studentin an der Ostfalia - Hochschule für angewandte Wissenschaften.<br> 
Studentische Hilfskraft am Institut für Information Engineering an der Ostfalia - Hochschule für angewandte Wissenschaften <br>
E-Mail: j.illgen@ostfalia.de](img/Julia.png)

</p>